CREATE TABLE Leads (
    id INT AUTO_INCREMENT,
    vortex_id VARCHAR(255) NOT NULL,
    lead_imported BOOLEAN DEFAULT FALSE,
    listing_status VARCHAR(255),
    name VARCHAR(255),
    name_2 VARCHAR(255),
    name_3 VARCHAR(255),
    name_4 VARCHAR(255),
    name_5 VARCHAR(255),
    name_6 VARCHAR(255),
    name_7 VARCHAR(255),
    mls_name VARCHAR(255),
    mls_name_2 VARCHAR(255),
    mls_name_3 VARCHAR(255),
    mls_name_4 VARCHAR(255),
    mls_name_5 VARCHAR(255),
    mls_name_6 VARCHAR(255),
    mls_name_7 VARCHAR(255),
    phone VARCHAR(20),
    phone_status VARCHAR(255),
    phone_2 VARCHAR(20),
    phone_2_status VARCHAR(255),
    phone_3 VARCHAR(20),
    phone_3_status VARCHAR(255),
    phone_4 VARCHAR(20),
    phone_4_status VARCHAR(255),
    phone_5 VARCHAR(20),
    phone_5_status VARCHAR(255),
    phone_6 VARCHAR(20),
    phone_6_status VARCHAR(255),
    phone_7 VARCHAR(20),
    phone_7_status VARCHAR(255),
    email VARCHAR(255),
    email_2 VARCHAR(255),
    email_3 VARCHAR(255),
    email_4 VARCHAR(255),
    email_5 VARCHAR(255),
    email_6 VARCHAR(255),
    email_7 VARCHAR(255),
    address TEXT,
    address_2 TEXT,
    address_3 TEXT,
    address_4 TEXT,
    address_5 TEXT,
    address_6 TEXT,
    address_7 TEXT,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    mailing_street VARCHAR(255),
    mailing_city VARCHAR(255),
    mailing_state VARCHAR(255),
    mailing_zip VARCHAR(20),
    list_date DATE,
    list_price DECIMAL(20, 2),
    days_on_market INT,
    lead_date DATE,
    expired_date DATE,
    withdrawn_date DATE,
    status_date DATE,
    listing_agent VARCHAR(255),
    listing_broker VARCHAR(255),
    mls_fsbo_id VARCHAR(255),
    absentee_owner BOOLEAN DEFAULT FALSE,
    property_address VARCHAR(255),
    property_city VARCHAR(255),
    property_state VARCHAR(255),
    property_zip VARCHAR(20),
    property_county VARCHAR(255),
    assigned_area VARCHAR(255),
    source VARCHAR(255),
    pipeline VARCHAR(255),
    buyer_seller VARCHAR(255),
    agent_assigned VARCHAR(255),

    PRIMARY KEY (id)
);